### ISSUE TITLE
Possible to integrate into appimaged

### ISSUE THREAD

**Issue by tyu1996** [probonopd/appwrapper#2]
I'm not sure if opening an issue for this is appropriate.

Just curious to know whether appwrapper is possible to be integrated into appimaged in the future. It will be useful that it looks like a set of daemon functions.

**Comment by probonopd** [comment]
Funny that you say it, I am just implementing this right now in an experimental appimaged implementation in Go. The code in this repo is for non-AppImage use cases though.

**Comment by probonopd** [comment]
Here:
https://github.com/probonopd/appimage/blob/master/src/appimaged/appwrapper.go
